# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1f426aab6f7470f0cdaeaae9a355a817372becae7985175a4c824db8cdc7072486437e8bdff924d6423dfc2af3083d0ab146ecce9fdf6da209c3bfd77a72b8

test:
  secret_key_base: eaaa8b00ed0d9196143117972bfe412e0f67d1a27795a03b1209d526f2814cb9a34c6e25998630fa9ba82c47e537439ba9a5b73ec03111acc4f800a9b31aec5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
